name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: veko
      run: |
        URL="https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${{ github.event.pull_request.number }}/files"
        FILES=$(curl -s -X GET -G $URL | jq -r '.[] | .yml')
        if echo $FILES | grep -q ".yml"; then
          echo "json file changed!!"
        else
          echo "no json file changed!!"
        fi
        echo $FILES