name: Node.js CI

on:
  push:
    branches: [ test ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: load changed files
      run: |
        URL="https://api.github.com/repos/${{ github.repository }}/pulls/2/files"
        FILES=$(curl -s -X   GET -H "Authorization: Bearer ${{ secrets.TOKEN }}" $URL | jq -r '.[] | .filename')
        echo "::set-output name=chfiles::$FILES"
      id: load-changed-files
    - name: Log changed files 
      run: echo "${{ steps.load-changed-files.outputs.chfiles }}"